spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  jpa:
    generate-ddl: true
  datasource:
    url: jdbc:mysql://db:3306/autoria-clone
    username: "user"
    password: "user1"
  mail:
    host: smtp.gmail.com
    port: 587
    username: letutanikita12@gmail.com
    password: eoywxgbdjgbahgfr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  secret: SUPER_SECRET_WORD_ABCEDRKAJSDLKJASD